ok brew git
ok brew tig
ok brew hub
ok brew vim
ok brew tmux
ok brew wget
ok brew rbenv
ok brew ruby-build
ok brew heroku
ok brew tmate
ok brew ag
ok brew redis
ok cask gpgtools
ok brew go
ok brew node
ok brew watch
ok brew sslscan
ok brew tree
ok brew gist
ok brew ctags
ok brew graphicsmagick
ok brew graphviz
ok brew httpie
ok brew hunspell
ok brew imagemagick
ok brew jq
ok brew readline
ok brew redis
ok brew sphinx
ok brew the_silver_searcher
ok brew watch
ok brew asciinema
